import java.util.Scanner;
class starter {
	public static void main(String args[]) {
		int [] x = new int[20];
		x[0] = 4;
		x[1] = 32;
		x[2] = 17;
		x[3] = 20;
		x[4] = 3;
		x[5] = 5;
		x[6] = 29;
		x[7] = 42;
		x[8] = 1;
		x[9] = 43;
		x[10] = 22;
		x[11] = 13; 
		x[12] = 33; 
		x[13] = 11; 
		x[14] = 44;
		x[15] = 8;
		x[16] = 24;
		x[17] = 9;
		x[18] = 23;
		x[19] = 10;
		
		System.out.println("These are the 20 numbers");
		System.out.print(x[0]);
		System.out.print(" ");
		System.out.print(x[1]);
		System.out.print(" ");
		System.out.print(x[2]);
		System.out.print(" ");
		System.out.print(x[3]);
		System.out.print(" ");
		System.out.print(x[4]);
		System.out.print(" ");
		System.out.print(x[5]);
		System.out.print(" ");
		System.out.print(x[6]);
		System.out.print(" ");
		System.out.print(x[7]);
		System.out.print(" ");
		System.out.print(x[8]);
		System.out.print(" ");
		System.out.print(x[9]);
		System.out.print(" ");
		System.out.print(x[10]);
		System.out.print(" ");
		System.out.print(x[11]);
		System.out.print(" ");
		System.out.print(x[12]);
		System.out.print(" ");
		System.out.print(x[13]);
		System.out.print(" ");
		System.out.print(x[14]);
		System.out.print(" ");
		System.out.print(x[15]);
		System.out.print(" ");
		System.out.print(x[16]);
		System.out.print(" ");
		System.out.print(x[17]);
		System.out.print(" ");
		System.out.print(x[18]);
		System.out.print(" ");
		System.out.println(x[19]);
		System.out.println();
		
		
		int [] y = new int[20];
		y[0] = 10;
		y[1] = 23;
		y[2] = 9;
		y[3] = 24;
		y[4] = 8;
		y[5] = 44;
		y[6] = 11;
		y[7] = 33;
		y[8] = 13;
		y[9] = 22;
		y[10] = 43;
		y[11] = 1; 
		y[12] = 42; 
		y[13] = 29; 
		y[14] = 5;
		y[15] = 3;
		y[16] = 20;
		y[17] = 17;
		y[18] = 32;
		y[19] = 4;
		
		System.out.println("These are those numbers backwards");
		System.out.print(y[0]);
		System.out.print(" ");
		System.out.print(y[1]);
		System.out.print(" ");
		System.out.print(y[2]);
		System.out.print(" ");
		System.out.print(y[3]);
		System.out.print(" ");
		System.out.print(y[4]);
		System.out.print(" ");
		System.out.print(y[5]);
		System.out.print(" ");
		System.out.print(y[6]);
		System.out.print(" ");
		System.out.print(y[7]);
		System.out.print(" ");
		System.out.print(y[8]);
		System.out.print(" ");
		System.out.print(y[9]);
		System.out.print(" ");
		System.out.print(y[10]);
		System.out.print(" ");
		System.out.print(y[11]);
		System.out.print(" ");
		System.out.print(y[12]);
		System.out.print(" ");
		System.out.print(y[13]);
		System.out.print(" ");
		System.out.print(y[14]);
		System.out.print(" ");
		System.out.print(y[15]);
		System.out.print(" ");
		System.out.print(y[16]);
		System.out.print(" ");
		System.out.print(y[17]);
		System.out.print(" ");
		System.out.print(y[18]);
		System.out.print(" ");
		System.out.print(y[19]);
}
}

